# Generated by Django 4.2.5 on 2023-09-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('uid', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('gacha_token', models.IntegerField(default=1)),
                ('order_token', models.IntegerField(default=1)),
                ('possessions', models.JSONField(default=list)),
            ],
        ),
    ]
