# Generated by Django 4.2.5 on 2023-09-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='uid',
            new_name='id',
        ),
    ]
