# Generated by Django 4.2.5 on 2023-09-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_data_possessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='possessions',
            field=models.JSONField(default=list),
        ),
    ]
