# Generated by Django 4.2.5 on 2023-09-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='num',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat', models.IntegerField()),
                ('name', models.CharField(default='null', max_length=200)),
            ],
        ),
    ]
