# Generated by Django 4.2.5 on 2023-09-18 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='camel_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=dict)),
                ('extra', models.JSONField(default=dict)),
                ('status', models.IntegerField(default=0)),
                ('complement', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camelorder.camel_order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user_data')),
            ],
        ),
        migrations.CreateModel(
            name='cp_inv_code',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camelorder.camel_order')),
            ],
        ),
    ]
