# Generated by Django 4.2.5 on 2023-09-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camelorder', '0002_alter_camel_order_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camel_order',
            name='complement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camelorder.camel_order'),
        ),
    ]
